const songs = [
    {
        title: "Jerosalema",
        author: "Master KG",
        styles: "Folk",
        upvotes: 2,
        downvotes: 5,
        isFavorited: false,
        price: 1000,
        lyrics: "O wanitwa mos, O wanitwa mos Master Master KG O wanitwa mos Jerusalema ikhaya lami Ngilondoloze Uhambe nami Zungangishiyi lana Jerusalema ikhaya lami Ngilondoloze Uhambe nami Zungangishiyi lana Ndawo yami ayikho lana Mbuso wami awukho lana Ngilondoloze Zuhambe nami Ndawo yami ayikho lana Mbuso wami awukho lana Ngilondoloze Zuhambe nami Ngilondoloze ngilondoloze ngilondoloze Zungangishiyi lana Ngilondoloze ngilondoloze ngilondoloze Zungangishiyi…",
        id: 1,
    },
    {
        title: "I have a drem",
        author: "Westlife",
        styles: "slow",
        upvotes: 20,
        downvotes: 13,
        isFavorited: false,
        price: 4050,
        lyrics: "I have a dream A song to sing To help me cope With anything If you see the wonder Of a fairy tale You can take the future Even if you fail I believe in angels Something good in everything I see I believe in angels When I know the time is right for me I'll cross the stream I have a dream, oh yeah I have a dream (I have a dream) A fantasy (fantasy) To help me through (help me through) Reality (reality) And my destination (destination) Makes it worth the while (worth the while) Pushing through the darkness (through the darkness) Still another mile (another mile) I believe in angels Something good in everything I see I believe in angels When I know the time is right for me I'll cross the stream (cross the stream) I have a dream I have a dream (oh yeah) A song to sing…",
        id: 2,
    },
    {
        title: "Manantena",
        author: "Ny Ainga",
        styles: "bassesa",
        upvotes: 5,
        downvotes: 3,
        isFavorited: false,
        price: 5000,
        lyrics: "Misento aho indraika malala Torovana mahatsiaro irery Kanefa ny toky tsy miala Manery ahy, ka tsy mbola very ref: Ho nofy ve ’zany andro izany Dia ’lay ora ,zay antenaintsika Tongava malaky, aza avela ho lany Ity fanantenana amintsika Ny adidy izay vitako etoana Dia hotontosaiko avokoa Porofo fa mbola tsy foana ilay toky andrandraintsika roa Hiandry aho ka hiandry hatrany Na mafy aza ny manantena Fo feno toky sikino hatrany Fa hoavy izany andro izany",
        id: 3,
    },
    {
        title: "Justin Bieber",
        author: "Love your self",
        styles: "rock",
        upvotes: 10,
        downvotes: 12,
        isFavorited: false,
        price: 10000,
        Llrics: "Cause if you like the way you look that much Oh baby, you should go and love yourself And if you think that I'm still holdin' on to",
        id: 4,
    },
    {
        title: "Talking to the moon",
        author: "Brino March",
        styles: "Rap",
        upvotes: 45,
        downvotes: 10,
        isFavorited: false,
        price: 8000,
        lyrics: "At night when the stars Light up my room I sit by myself Talking to the moon Tryna get to you In hopes you're on The other side Talking to me too Or am I a fool Who sits alone Talking to the moon Oh",
        id: 5,
    },
    {
        title: "Remember me",
        author: "Lucky Dube",
        styles: "Reggae",
        upvotes: 15,
        downvotes: 45,
        isFavorited: false,
        price: 2000,
        lyrics: "Mother died of a heart attack Many years ago when she heard That you were married again Now, I'm the only one left in the family",
        id: 6,
    },
    {
        title: "400 volt",
        author: "Wawa",
        styles: "Salegy",
        upvotes: 100,
        downvotes: 10,
        isFavorited: false,
        price: 3000,
        lyrics: "vas y maman dance maman, dansé x4 stop dance papa, dansé x 4 stop danse petit, dansé x 4",
        id: 7,
    }
]

export default songs;